version: "3"

services:
  gpsd:
    build: ./gpsd
    devices:
      - "/dev/serial0:/dev/gps0"
  ros:
    build:
      context: ../..
      dockerfile: ./docker/earth_rover/ros/Dockerfile
    depends_on:
      - gpsd
